//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transference.Shared {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DiccionaryMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DiccionaryMessage() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transference.Shared.DiccionaryMessage", typeof(DiccionaryMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Credenciales incorrectas. Intenta nuevamente !!.
        /// </summary>
        public static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Las credenciales no pueden estar vacías !!.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! No se pudo cargar el tiempo extra..!!.
        /// </summary>
        public static string ErrorChange {
            get {
                return ResourceManager.GetString("ErrorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Ocurrió un error al recuperar el estado del fichaje. !!.
        /// </summary>
        public static string ErrorRetrievingState {
            get {
                return ResourceManager.GetString("ErrorRetrievingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Error al intentar iniciar sesión !!.
        /// </summary>
        public static string ErrorSesion {
            get {
                return ResourceManager.GetString("ErrorSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Has cerrado sesión correctamente. !!.
        /// </summary>
        public static string ExitSesion {
            get {
                return ResourceManager.GetString("ExitSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! No se pudo recuperar el estado actual del fichaje desde el servidor. !!.
        /// </summary>
        public static string FailedToRetrieveState {
            get {
                return ResourceManager.GetString("FailedToRetrieveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Error obteniendo el token !!.
        /// </summary>
        public static string GetErrorToken {
            get {
                return ResourceManager.GetString("GetErrorToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! El identificador de usuario proporcionado no es válido. !!.
        /// </summary>
        public static string InvalidUserId {
            get {
                return ResourceManager.GetString("InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! Error al realizar la solicitud de login !!.
        /// </summary>
        public static string RequestLogin {
            get {
                return ResourceManager.GetString("RequestLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! No se puede iniciar sesión. Verifica tus credenciales !!.
        /// </summary>
        public static string Sesion {
            get {
                return ResourceManager.GetString("Sesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! La solicitud de login excedió el tiempo de espera !!.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! El token de autenticación ha expirado. Por favor, vuelva a iniciar sesión. !!.
        /// </summary>
        public static string TokenError {
            get {
                return ResourceManager.GetString("TokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! &quot;El token no es válido !!.
        /// </summary>
        public static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a !! No se encontró el token en el almacenamiento.!!.
        /// </summary>
        public static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
    }
}
